# Generated by Django 5.2.1 on 2025-05-09 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapeta', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('raza', models.CharField(max_length=100)),
                ('estado_reproductivo', models.CharField(choices=[('gestante', 'Gestante'), ('lactante', 'Lactante'), ('vacío', 'Vacío'), ('castrado', 'Castrado')], max_length=20)),
                ('estado_productivo', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('engorde', 'Engorde')], max_length=20)),
                ('salud', models.JSONField(blank=True, default=list)),
                ('produccion', models.JSONField(blank=True, default=list)),
                ('peso_actual', models.FloatField(blank=True, null=True)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('historial_movimientos', models.JSONField(blank=True, default=list)),
                ('fecha_alta_sistema', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_baja_sistema', models.DateTimeField(blank=True, null=True)),
                ('foto_perfil_url', models.URLField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales_creados', to=settings.AUTH_USER_MODEL)),
                ('descendencia', models.ManyToManyField(blank=True, to='animales.animal')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
