# Generated by Django 5.2.1 on 2025-05-11 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=50)),
                ('duracion', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('administrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='animales.animal')),
            ],
        ),
    ]
