# Generated by Django 5.2.1 on 2025-05-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('produccion', 'Producción'), ('gestacion', 'Gestación'), ('tratamiento', 'Tratamiento')], max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_ids', models.ManyToManyField(related_name='grupos', to='animales.animal')),
            ],
        ),
    ]
